export const conditionList = [
    { _id: "1", value: "Cardiomegaly" },
    { _id: "2", value: "Arrhythmia" },
    { _id: "3", value: "Heart stroke" },
    { _id: "4", value: "Atrial fibrillation" },
    { _id: "5", value: "Hypertension" },
    { _id: "6", value: "Coronary artery disease" },
    { _id: "7", value: "Congestive heart failure" },
    { _id: "8", value: "Myocarditis" },
    { _id: "9", value: "Pericarditis" },
    { _id: "10", value: "Valvular heart disease" },
    { _id: "11", value: "Bradycardia" },
    { _id: "12", value: "Tachycardia" },
    { _id: "13", value: "Palpitations" },
    { _id: "14", value: "Angina" },
    { _id: "15", value: "Heart murmur" },
    { _id: "16", value: "Mitral valve prolapse" },
    { _id: "17", value: "Endocarditis" },
    { _id: "18", value: "Pulmonary hypertension" },
    { _id: "19", value: "Ischemic heart disease" },
    { _id: "20", value: "Ventricular fibrillation" },
    { _id: "21", value: "Stroke" },
    { _id: "22", value: "Transient ischemic attack" },
    { _id: "23", value: "Epilepsy" },
    { _id: "24", value: "Multiple sclerosis" },
    { _id: "25", value: "Parkinson’s disease" },
    { _id: "26", value: "Alzheimer’s disease" },
    { _id: "27", value: "Migraines" },
    { _id: "28", value: "Peripheral neuropathy" },
    { _id: "29", value: "Seizure disorder" },
    { _id: "30", value: "Brain tumor" },
    { _id: "31", value: "Spinal cord injury" },
    { _id: "32", value: "Vertigo" },
    { _id: "33", value: "Sleep apnea" },
    { _id: "34", value: "Diabetes type 1" },
    { _id: "35", value: "Diabetes type 2" },
    { _id: "36", value: "Gestational diabetes" },
    { _id: "37", value: "Hypoglycemia" },
    { _id: "38", value: "Hyperglycemia" },
    { _id: "39", value: "Thyroid disorder" },
    { _id: "40", value: "Hyperthyroidism" },
    { _id: "41", value: "Hypothyroidism" },
    { _id: "42", value: "Addison’s disease" },
    { _id: "43", value: "Cushing’s syndrome" },
    { _id: "44", value: "Obesity" },
    { _id: "45", value: "Anemia" },
    { _id: "46", value: "Leukemia" },
    { _id: "47", value: "Lymphoma" },
    { _id: "48", value: "Hemophilia" },
    { _id: "49", value: "Thalassemia" },
    { _id: "50", value: "Sickle cell disease" },
    { _id: "51", value: "Asthma" },
    { _id: "52", value: "COPD" },
    { _id: "53", value: "Bronchitis" },
    { _id: "54", value: "Emphysema" },
    { _id: "55", value: "Tuberculosis" },
    { _id: "56", value: "Pneumonia" },
    { _id: "57", value: "Pulmonary fibrosis" },
    { _id: "58", value: "Cystic fibrosis" },
    { _id: "59", value: "Chronic cough" },
    { _id: "60", value: "Lung cancer" },
    { _id: "61", value: "Kidney stones" },
    { _id: "62", value: "Chronic kidney disease" },
    { _id: "63", value: "Renal failure" },
    { _id: "64", value: "Urinary tract infection" },
    { _id: "65", value: "Prostate enlargement" },
    { _id: "66", value: "Polycystic kidney disease" },
    { _id: "67", value: "Hepatitis A" },
    { _id: "68", value: "Hepatitis B" },
    { _id: "69", value: "Hepatitis C" },
    { _id: "70", value: "Cirrhosis" },
    { _id: "71", value: "Fatty liver disease" },
    { _id: "72", value: "Gallstones" },
    { _id: "73", value: "Pancreatitis" },
    { _id: "74", value: "Irritable bowel syndrome" },
    { _id: "75", value: "Crohn’s disease" },
    { _id: "76", value: "Ulcerative colitis" },
    { _id: "77", value: "Celiac disease" },
    { _id: "78", value: "Gastroesophageal reflux disease" },
    { _id: "79", value: "Peptic ulcer" },
    { _id: "80", value: "Constipation" },
    { _id: "81", value: "Diarrhea" },
    { _id: "82", value: "Hemorrhoids" },
    { _id: "83", value: "Glaucoma" },
    { _id: "84", value: "Cataracts" },
    { _id: "85", value: "Macular degeneration" },
    { _id: "86", value: "Retinal detachment" },
    { _id: "87", value: "Conjunctivitis" },
    { _id: "88", value: "Otitis media" },
    { _id: "89", value: "Hearing loss" },
    { _id: "90", value: "Tinnitus" },
    { _id: "91", value: "Vertigo (ear)" },
    { _id: "92", value: "Psoriasis" },
    { _id: "93", value: "Eczema" },
    { _id: "94", value: "Rosacea" },
    { _id: "95", value: "Acne" },
    { _id: "96", value: "Skin cancer" },
    { _id: "97", value: "Lupus" },
    { _id: "98", value: "Rheumatoid arthritis" },
    { _id: "99", value: "Osteoarthritis" },
    { _id: "100", value: "Gout" },
    { _id: "101", value: "Fibromyalgia" },
    { _id: "102", value: "Other" }
  ];
  