export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAILURE = "APPOINTMENT_CREATE_FAILURE";

export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAILURE = "APPOINTMENT_UPDATE_FAILURE";

export const APPOINTMENT_GET_REQUEST = "APPOINTMENT_GET_REQUEST";
export const APPOINTMENT_GET_SUCCESS = "APPOINTMENT_GET_SUCCESS";
export const APPOINTMENT_GET_FAILURE = "APPOINTMENT_GET_FAILURE";

export const APPOINTMENT_DELETE_REQUEST = "APPOINTMENT_DELETE_REQUEST";
export const APPOINTMENT_DELETE_SUCCESS = "APPOINTMENT_DELETE_SUCCESS";
export const APPOINTMENT_DELETE_FAILURE = "APPOINTMENT_DELETE_FAILURE";

export const APPOINTMENT_LIST_BY_DOCTOR_REQUEST =
    "APPOINTMENT_LIST_BY_DOCTOR_REQUEST";
export const APPOINTMENT_LIST_BY_DOCTOR_SUCCESS =
    "APPOINTMENT_LIST_BY_DOCTOR_SUCCESS";
export const APPOINTMENT_LIST_BY_DOCTOR_FAILURE =
    "APPOINTMENT_LIST_BY_DOCTOR_FAILURE";

export const APPOINTMENT_LIST_AVAILABLE_REQUEST =
    "APPOINTMENT_LIST_AVAILABLE_REQUEST";
export const APPOINTMENT_LIST_AVAILABLE_SUCCESS =
    "APPOINTMENT_LIST_AVAILABLE_SUCCESS";
export const APPOINTMENT_LIST_AVAILABLE_FAILURE =
    "APPOINTMENT_LIST_AVAILABLE_FAILURE";
