export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAILURE = "APPOINTMENT_CREATE_FAILURE";

export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAILURE = "APPOINTMENT_UPDATE_FAILURE";

export const APPOINTMENT_GET_REQUEST = "APPOINTMENT_GET_REQUEST";
export const APPOINTMENT_GET_SUCCESS = "APPOINTMENT_GET_SUCCESS";
export const APPOINTMENT_GET_FAILURE = "APPOINTMENT_GET_FAILURE";
