export const AVAILABILITY_CREATE_REQUEST = "AVAILABILITY_CREATE_REQUEST";
export const AVAILABILITY_CREATE_SUCCESS = "AVAILABILITY_CREATE_SUCCESS";
export const AVAILABILITY_CREATE_FAILURE = "AVAILABILITY_CREATE_FAILURE";

export const AVAILABILITY_UPDATE_REQUEST = "AVAILABILITY_UPDATE_REQUEST";
export const AVAILABILITY_UPDATE_SUCCESS = "AVAILABILITY_UPDATE_SUCCESS";
export const AVAILABILITY_UPDATE_FAILURE = "AVAILABILITY_UPDATE_FAILURE";

export const AVAILABILITY_GET_REQUEST = "AVAILABILITY_GET_REQUEST";
export const AVAILABILITY_GET_SUCCESS = "AVAILABILITY_GET_SUCCESS";
export const AVAILABILITY_GET_FAILURE = "AVAILABILITY_GET_FAILURE";

export const AVAILABILITIES_BY_DOCTOR_REQUEST =
    "AVAILABILITIES_BY_DOCTOR_REQUEST";
export const AVAILABILITIES_BY_DOCTOR_SUCCESS =
    "AVAILABILITIES_BY_DOCTOR_SUCCESS";
export const AVAILABILITIES_BY_DOCTOR_FAILURE =
    "AVAILABILITIES_BY_DOCTOR_FAILURE";