export const DOCTOR_NOTE_CREATE_REQUEST = "DOCTOR_NOTE_CREATE_REQUEST";
export const DOCTOR_NOTE_CREATE_SUCCESS = "DOCTOR_NOTE_CREATE_SUCCESS";
export const DOCTOR_NOTE_CREATE_FAILURE = "DOCTOR_NOTE_CREATE_FAILURE";

export const DOCTOR_NOTE_GET_REQUEST = "DOCTOR_NOTE_GET_REQUEST";
export const DOCTOR_NOTE_GET_SUCCESS = "DOCTOR_NOTE_GET_SUCCESS";
export const DOCTOR_NOTE_GET_FAILURE = "DOCTOR_NOTE_GET_FAILURE";