export const DOCTOR_CREATE_REQUEST = "DOCTOR_CREATE_REQUEST";
export const DOCTOR_CREATE_SUCCESS = "DOCTOR_CREATE_SUCCESS";
export const DOCTOR_CREATE_FAILURE = "DOCTOR_CREATE_FAILURE";

export const DOCTOR_UPDATE_REQUEST = "DOCTOR_UPDATE_REQUEST";
export const DOCTOR_UPDATE_SUCCESS = "DOCTOR_UPDATE_SUCCESS";
export const DOCTOR_UPDATE_FAILURE = "DOCTOR_UPDATE_FAILURE";

export const DOCTOR_GET_REQUEST = "DOCTOR_GET_REQUEST";
export const DOCTOR_GET_SUCCESS = "DOCTOR_GET_SUCCESS";
export const DOCTOR_GET_FAILURE = "PATIENT_GET_FAILURE";