// Fetch all health conditions
export const FETCH_HEALTH_CONDITIONS_REQUEST = "FETCH_HEALTH_CONDITIONS_REQUEST";
export const FETCH_HEALTH_CONDITIONS_SUCCESS = "FETCH_HEALTH_CONDITIONS_SUCCESS";
export const FETCH_HEALTH_CONDITIONS_FAILURE = "FETCH_HEALTH_CONDITIONS_FAILURE";

// Fetch secondary specializations mapped from a health condition
export const FETCH_SECONDARY_SPECIALIZATIONS_REQUEST = "FETCH_SECONDARY_SPECIALIZATIONS_REQUEST";
export const FETCH_SECONDARY_SPECIALIZATIONS_SUCCESS = "FETCH_SECONDARY_SPECIALIZATIONS_SUCCESS";
export const FETCH_SECONDARY_SPECIALIZATIONS_FAILURE = "FETCH_SECONDARY_SPECIALIZATIONS_FAILURE";

// Fetch doctors based on secondary specializations
export const FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_REQUEST = "FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_REQUEST";
export const FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_SUCCESS = "FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_SUCCESS";
export const FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_FAILURE = "FETCH_DOCTORS_BY_SECONDARY_SPECIALIZATION_FAILURE";
