export const IMAGE_RECOGNITION_GET_REQUEST = 'IMAGE_RECOGNITION_GET_REQUEST';
export const IMAGE_RECOGNITION_GET_SUCCESS = 'IMAGE_RECOGNITION_GET_SUCCESS';
export const IMAGE_RECOGNITION_GET_FAILURE = 'IMAGE_RECOGNITION_GET_FAILURE';
