export const LAB_TEST_RESULT_CREATE_REQUEST = "LAB_TEST_RESULT_CREATE_REQUEST";
export const LAB_TEST_RESULT_CREATE_SUCCESS = "LAB_TEST_RESULT_CREATE_SUCCESS";
export const LAB_TEST_RESULT_CREATE_FAILURE = "LAB_TEST_RESULT_CREATE_FAILURE";

export const LAB_TEST_RESULT_GET_REQUEST = "LAB_TEST_RESULT_GET_REQUEST";
export const LAB_TEST_RESULT_GET_SUCCESS = "LAB_TEST_RESULT_GET_SUCCESS";
export const LAB_TEST_RESULT_GET_FAILURE = "LAB_TEST_RESULT_GET_FAILURE";

export const LAB_TEST_RESULT_GET_BY_PATIENT_REQUEST =
  "LAB_TEST_RESULT_GET_BY_PATIENT_REQUEST";
export const LAB_TEST_RESULT_GET_BY_PATIENT_SUCCESS =
  "LAB_TEST_RESULT_GET_BY_PATIENT_SUCCESS";
export const LAB_TEST_RESULT_GET_BY_PATIENT_FAILURE =
  "LAB_TEST_RESULT_GET_BY_PATIENT_FAILURE";
