export const MEDICAL_MASTERDATA_REQUEST = 'MEDICAL_MASTERDATA_REQUEST';
export const MEDICAL_MASTERDATA_SUCCESS = 'MEDICAL_MASTERDATA_SUCCESS';
export const MEDICAL_MASTERDATA_FAIL = 'MEDICAL_MASTERDATA_FAIL';