export const PATIENT_CREATE_REQUEST = "PATIENT_CREATE_REQUEST"
export const PATIENT_CREATE_SUCCESS = "PATIENT_CREATE_SUCCESS"
export const PAITENT_CREATE_FAILURE = "PATIENT_CREATE_FAILURE"


export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST"
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS"
export const PATIENT_DETAILS_FAILURE = "PATIENT_DETAILS_FAILURE"    
