export const PATIENT_STORIES_LIST_BY_DOCTOR_REQUEST = "PATIENT_STORIES_LIST_BY_DOCTOR_REQUEST";
export const PATIENT_STORIES_LIST_BY_DOCTOR_SUCCESS = "PATIENT_STORIES_LIST_BY_DOCTOR_SUCCESS";
export const PATIENT_STORIES_LIST_BY_DOCTOR_FAILURE = "PATIENT_STORIES_LIST_BY_DOCTOR_FAILURE";

export const PATIENT_STORY_CREATE_REQUEST = "PATIENT_STORY_CREATE_REQUEST";
export const PATIENT_STORY_CREATE_SUCCESS = "PATIENT_STORY_CREATE_SUCCESS";
export const PATIENT_STORY_CREATE_FAILURE = "PATIENT_STORY_CREATE_FAILURE";
