export const PATIENT_CREATE_REQUEST = "PATIENT_CREATE_REQUEST";
export const PATIENT_CREATE_SUCCESS = "PATIENT_CREATE_SUCCESS";
export const PAITENT_CREATE_FAILURE = "PATIENT_CREATE_FAILURE";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PAITENT_UPDATE_FAILURE = "PATIENT_UPDATE_FAILURE";

export const PATIENT_GET_REQUEST = "PATIENT_GET_REQUEST";
export const PATIENT_GET_SUCCESS = "PATIENT_GET_SUCCESS";
export const PATIENT_GET_FAILURE = "PATIENT_GET_FAILURE";
