export const PRESCRIPTION_IMAGE_CREATE_REQUEST = "PRESCRIPTION_IMAGE_CREATE_REQUEST";
export const PRESCRIPTION_IMAGE_CREATE_SUCCESS = "PRESCRIPTION_IMAGE_CREATE_SUCCESS";
export const PRESCRIPTION_IMAGE_CREATE_FAILURE = "PRESCRIPTION_IMAGE_CREATE_FAILURE";

export const PRESCRIPTION_IMAGE_GET_REQUEST = "PRESCRIPTION_IMAGE_GET_REQUEST";
export const PRESCRIPTION_IMAGE_GET_SUCCESS = "PRESCRIPTION_IMAGE_GET_SUCCESS";
export const PRESCRIPTION_IMAGE_GET_FAILURE = "PRESCRIPTION_IMAGE_GET_FAILURE";
