export const PRESCRIPTION_CREATE_REQUEST = "PRESCRIPTION_CREATE_REQUEST";
export const PRESCRIPTION_CREATE_SUCCESS = "PRESCRIPTION_CREATE_SUCCESS";
export const PRESCRIPTION_CREATE_FAILURE = "PRESCRIPTION_CREATE_FAILURE";

export const PRESCRIPTION_GET_REQUEST = "PRESCRIPTION_GET_REQUEST";
export const PRESCRIPTION_GET_SUCCESS = "PRESCRIPTION_GET_SUCCESS";
export const PRESCRIPTION_GET_FAILURE = "PRESCRIPTION_GET_FAILURE";

export const PRESCRIPTION_LIST_REQUEST = "PRESCRIPTION_LIST_REQUEST";
export const PRESCRIPTION_LIST_SUCCESS = "PRESCRIPTION_LIST_SUCCESS";
export const PRESCRIPTION_LIST_FAILURE = "PRESCRIPTION_LIST_FAILURE";
