export const PRIMARY_SPECIALIZATION_REQUEST = "PRIMARY_SPECIALIZATION_REQUEST";
export const PRIMARY_SPECIALIZATION_SUCCESS = "PRIMARY_SPECIALIZATION_SUCCESS";
export const PRIMARY_SPECIALIZATION_FAILURE = "PRIMARY_SPECIALIZATION_FAILURE";
