export const PRIMARY_SPECIALIZATION_REQUEST = "PRIMARY_SPECIALIZATION_REQUEST";
export const PRIMARY_SPECIALIZATION_SUCCESS = "PRIMARY_SPECIALIZATION_SUCCESS";
export const PRIMARY_SPECIALIZATION_FAILURE = "PRIMARY_SPECIALIZATION_FAILURE";

export const PRIMARY_TO_SECONDARY_REQUEST = "PRIMARY_TO_SECONDARY_REQUEST";
export const PRIMARY_TO_SECONDARY_SUCCESS = "PRIMARY_TO_SECONDARY_SUCCESS";
export const PRIMARY_TO_SECONDARY_FAILURE = "PRIMARY_TO_SECONDARY_FAILURE";