export const SECONDARY_SPECIALIZATION_REQUEST = "SECONDARY_SPECIALIZATION_REQUEST";
export const SECONDARY_SPECIALIZATION_SUCCESS = "SECONDARY_SPECIALIZATION_SUCCESS";
export const SECONDARY_SPECIALIZATION_FAILURE = "SECONDARY_SPECIALIZATION_FAILURE";
