export const UMA_CHAT_LIST_REQUEST = "UMA_CHAT_LIST_REQUEST";
export const UMA_CHAT_LIST_SUCCESS = "UMA_CHAT_LIST_SUCCESS";
export const UMA_CHAT_LIST_FAILURE = "UMA_CHAT_LIST_FAILURE";

export const UMA_CHAT_CREATE_REQUEST = "UMA_CHAT_CREATE_REQUEST";
export const UMA_CHAT_CREATE_SUCCESS = "UMA_CHAT_CREATE_SUCCESS";
export const UMA_CHAT_CREATE_FAILURE = "UMA_CHAT_CREATE_FAILURE";

export const UMA_CHAT_REMOVE_TYPING_MESSAGE = "UMA_CHAT_REMOVE_TYPING_MESSAGE";
