export const activityActionTypes = {
  FETCH_ACTIVITY_RATE : "FETCH_ACTIVITY_RATE",
  FETCH_ACTIVITY_INTRADAY: "FETCH_ACTIVITY_INTRADAY",
  FETCH_ACTIVITY_TRENDCARD: "FETCH_ACTIVITY_TRENDCARD",
  FETCH_DASHBOARD_ACTIVITY_TRENDCARD: "FETCH_DASHBOARD_ACTIVITY_TRENDCARD",
  EMPTY_ACTIVITY_DATA: "EMPTY_ACTIVITY_DATA",
  SET_ACTIVITY_INTRADAY_DATA: "SET_ACTIVITY_INTRADAY_DATA",
  SET_ACTIVITY_DATA: "SET_ACTIVITY_DATA",    
}