export const foodActionTypes = {
  FETCH_FOOD_DATA : "FETCH_FOOD_DATA",
  FETCH_FOOD_TRENDCARD: "FETCH_FOOD_TRENDCARD",
  FETCH_DASHBOARD_FOOD_TRENDCARD: "FETCH_DASHBOARD_FOOD_TRENDCARD",
  EMPTY_FOOD_DATA: "EMPTY_FOOD_DATA",
  SET_FOOD_DATA: "SET_FOOD_DATA",
  DELETE_FOOD_DATA: "DELETE_FOOD_DATA"
}