export const profileActionTypes = {
  SET_PROFILE_DATA: "SET_PROFILE_DATA",
  ADD_AVATAR: "ADD_AVATAR",
  UPDATE_DEVICES: "UPDATE_DEVICES",
  SELECT_DEVICE: "SELECT_DEVICE",
  SET_SURVEY: "SET_SURVEY"
}