export const deviceActionTypes = {
  SET_DEVICE_SELECTED: "SET_DEVICE_SELECTED",
  FETCH_DEVICES: "FETCH_DEVICES",
  SET_DEVICES: "SET_DEVICES",
  SELECT_NEXT_DEVICE: "SELECT_NEXT_DEVICE",
  SELECT_PREVIOUS_DEVICE: "SELECT_PREVIOUS_DEVICE",
  SET_SYNC_LOADING: "SET_SYNC_LOADING"
}