export const userAuthActionTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  LOGIN_USER_WITH_EMAIL: "LOGIN_USER_WITH_EMAIL",
  LOGIN_USER_WITH_PASSWORD: "LOGIN_USER_WITH_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  SET_LOADING: "SET_LOADING",
  LOGOUT_USER: "LOGOUT_USER",
  SET_HEARTRATE_DATA_LOADING: "SET_HEARTRATE_LOADING",
  SET_SLEEP_DATA_LOADING: "SET_SLEEP_DATA_LOADING",
  SET_EMAIL_FOR_OTP: "SET_EMAIL_FOR_OTP",
  SHOW_SKIP_ON_ADD_DEVICE: "SHOW_SKIP_ON_ADD_DEVICE",
  START_TOUR_GUIDE: "START_TOUR_GUIDE",
}