/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://aayezbhftjezdlcfxzfcg66qhu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-byvr7funmjajvpcqkdekmoj6oe",
    "aws_cognito_identity_pool_id": "us-east-1:a780d1ef-8c87-4896-b42d-52516bf8d883",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xGuCoR5zO",
    "aws_user_pools_web_client_id": "6atqhjo3elkgoiiamif6f1t76o",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mybeats-profile-imagesefa9b-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
